### PR TITLE
Next UI v1: A new user interface approach

### PR DESCRIPTION
**Pull request by juehv**
I developed and tested a new interface approach for the Explorer HAT rigs. Would be nice if we can add the modifications to the official repostitory to make it easier for other people to test it. I made some documentation in the readme.md.

### CODE REVIEW

**Comment by scottleibrand** [comment]
@cluckj would you like to take a look at this? I don't have an active Pi HAT rig at the moment.

**Comment by juehv** [comment]
@scottleibrand @cluckj Just wanted to remind this pull request. Maybe it's possible to merge it without doublechecking it? I mean I test the interface since I sent the pull request and didn't experience big issues. Also it's the dev branch which is not used by any scripts. User would have to install it by hand anyway... Cheers!

**Comment by scottleibrand** [comment]
Sure, I can do that, if you can fix the merge conflicts that have developed in the mean time.

**Comment by juehv** [comment]
@scottleibrand I managed to make it compatible :)

**Pull request merged**
